version: '3.9'

services:
  slam-security-db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql_log:/var/log/mysql
      - ./mysql_conf:/etc/mysql/mysql.conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  slam_security_webserver:
    depends_on:
      - db
    build: .
    volumes:
      - ./webserver:/var/www/html
    ports:
      - 82:80

    environment:
      MYSQL_DB_HOST: slam-security-db:3306
      CATA_DB_USER: root
      CATA_DB_PASSWORD: example
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data_flop:

